services:
  blobfish:
    build: .
    ports:
      - "31415:8080"
    volumes:
      - blobfish-data:/data/blobfish
      - ./dev.toml:/etc/blobfish/config.toml:ro
    environment:
      RUST_LOG: blobfish=debug,tower_http=info

volumes:
  blobfish-data: